### ISSUE TITLE
Not Showing since update between 3.1-3.2

### ISSUE THREAD

**Issue by floyega** [MinMao-Hub/PasteEasy#1]
I did not update the app since 3.0, but I recently did so a few days ago.

Not sure what happened between update 3.1 - 3.2, but after I updated the app via Mac App Store, PasteEasy Clipboard no longer shows.

Everything else shows, including the top menu icon and the dropdown menu, the preferences window, and all the settings seem to engage. However the PasteEasy Clipboard no longer shows when I press command + shift + v or even when I adjust it's position from Up, Down, Left or Right from the preferences window.

Running the latest version of Catalina 10.15.7

I would like to delete the app's preferences to see if that will help, but I fear of deleting my clipboard history. I have deleted the app and reinstalled it, with the same issue even after a restart.

**Comment by floyega** [comment]
Also! The drop down menu states it's still version 3.1 and not 3.2

**Comment by MinMao-Hub** [comment]
> I did not update the app since 3.0, but I recently did so a few days ago.
> 
> Not sure what happened between update 3.1 - 3.2, but after I updated the app via Mac App Store, PasteEasy Clipboard no longer shows.
> 
> Everything else shows, including the top menu icon and the dropdown menu, the preferences window, and all the settings seem to engage. However the PasteEasy Clipboard no longer shows when I press command + shift + v or even when I adjust it's position from Up, Down, Left or Right from the preferences window.
> 
> Running the latest version of Catalina 10.15.7
> 
> I would like to delete the app's preferences to see if that will help, but I fear of deleting my clipboard history. I have deleted the app and reinstalled it, with the same issue even after a restart.

This is a known problem and will be fixed in the next version.
You can try to turn off the external screen display option in preferences-> more tab.

**Comment by MinMao-Hub** [comment]
> Also! The drop down menu states it's still version 3.1 and not 3.2

Yes, this is a display bug, which is actually 3.2

**Comment by MinMao-Hub** [comment]
Please download the latest version

**Comment by MinMao-Hub** [comment]
> Also! The drop down menu states it's still version 3.1 and not 3.2

Please download the latest version: 3.4
