### ISSUE TITLE
突然闪退重启后，之前粘贴板的内容都清空了

### ISSUE THREAD

**Issue by clearzhou** [MinMao-Hub/PasteEasy#10]
<img width="550" alt="image" src="https://user-images.githubusercontent.com/62474563/217418809-066f1df3-6bc4-412f-bfbd-cdc4195822a5.png">
现在是只要退出重新打开后就会清空粘贴板吗？
- 重启电脑
- 闪退
- 主动退出app
还是更希望保留之前能够记住所有粘贴板内容的设计。

**Comment by MinMao-Hub** [comment]
现在所有数据都存储在Documents文件夹下面，除非用户主动清除，不会自动清除数据的

**Comment by clearzhou** [comment]
![image](https://user-images.githubusercontent.com/62474563/217431219-08099c32-6f88-44c4-ae11-1dcbdf511250.png)
![image](https://user-images.githubusercontent.com/62474563/217431305-9ef6ed2f-c064-4535-a626-acfd4f71dcd6.png)
我看了一下我这边确实是每次都会清除，可以问一下要怎么调整吗？

**Comment by MinMao-Hub** [comment]
麻烦，加我的微信，直接沟通看一下: mp12860

**Comment by MinMao-Hub** [comment]
/Users/xxxxx/Library/Containers/com.minmao.paste/Data/Library/Preferences/com.minmao.paste.plist  这个文件给我发一下

**Comment by MinMao-Hub** [comment]
暂时把历史存储数量调整为500，下个版本优化
