### ISSUE TITLE
显示 PasteEasy 面板速度自定义

### ISSUE THREAD

**Issue by ZCY01** [MinMao-Hub/PasteEasy#11]
显示 PasteEasy 面板 速度过慢。

**Comment by MinMao-Hub** [comment]
> 显示 PasteEasy 面板 速度过慢。

将在下个版本中增加偏好设置选项，敬请期待

**Comment by MinMao-Hub** [comment]
请更新到3.7版本；让后在偏好设置中修改展示关闭速度

![speed](https://user-images.githubusercontent.com/9302381/227821157-4de1dd9b-2900-4ab9-a5b2-1a1ddbe23dd1.png)
