### ISSUE TITLE
粘贴板history 是空的

### ISSUE THREAD

**Issue by AkaiNoCat** [MinMao-Hub/PasteEasy#12]
![image](https://user-images.githubusercontent.com/46026384/218382756-7b8bbade-6cce-4091-b380-5afe715b960f.png)

**Comment by MinMao-Hub** [comment]
> ![image](https://user-images.githubusercontent.com/46026384/218382756-7b8bbade-6cce-4091-b380-5afe715b960f.png)

MacOS 11的系统 ？

**Comment by AkaiNoCat** [comment]
> 

是嘞，我升级试试

**Comment by MinMao-Hub** [comment]
> > 
> 
> 是嘞，我升级试试

升级是好的 -  这个问题之前有人给我反馈了【他的系统是11.6.5】。。   目前没找到解决方案 - 只能暂时搁置了

**Comment by AkaiNoCat** [comment]
> > > 
> > 
> > 
> > 是嘞，我升级试试
> 
> 升级是好的 - 这个问题之前有人给我反馈了【他的系统是11.6.5】。。 目前没找到解决方案 - 只能暂时升级系统版本来解决了

升级后解决啦，谢啦
