### ISSUE TITLE
Pasteboard突然空了

### ISSUE THREAD

**Issue by codeskyblue** [MinMao-Hub/PasteEasy#13]
![image](https://user-images.githubusercontent.com/3281689/220508696-f38c3ad7-a0f9-469f-9f49-fd658ddacd94.png)

复制了内容，但是里面什么也没有。目前用的M1 Macbook Pro, 设置中已经添加了辅助功能隐私权限

**Comment by MinMao-Hub** [comment]
> ![image](https://user-images.githubusercontent.com/3281689/220508696-f38c3ad7-a0f9-469f-9f49-fd658ddacd94.png)
> 
> 复制了内容，但是里面什么也没有。目前用的M1 Macbook Pro, 设置中已经添加了辅助功能隐私权限

MacOS 11.x 版本目前有这个问题，建议升级系统版本 【PS：我这边实在不方便复现 -  没有11.x的测试环境】

**Comment by codeskyblue** [comment]
需要什么日志我可以提供，目前电脑都系统不方便升级。这个issue可以reopen不

**Comment by MinMao-Hub** [comment]
> 需要什么日志我可以提供，目前电脑都系统不方便升级。这个issue可以reopen不

OK   你这边方便的话，加我微信， 然后我给你发包进行测试

**Comment by shuosiw** [comment]
遇到同样的问题，之前版本是正常的..黑苹果升级比较折腾，有没什么不升级系统的解决方案哇？

**Comment by MinMao-Hub** [comment]
> 遇到同样的问题，之前版本是正常的..黑苹果升级比较折腾，有没什么不升级系统的解决方案哇？

已经排查到问题，将在下个版本中修复，敬请期待！

**Comment by MinMao-Hub** [comment]
该问题已在3.7版本中修复， 请更新App版本；

**Comment by shuosiw** [comment]
后面我卸载了重装就好了...就是之前钉起来的一些数据没了..估计是有些保存的粘贴历史有问题...

**Comment by MinMao-Hub** [comment]
> 后面我卸载了重装就好了...就是之前钉起来的一些数据没了..估计是有些保存的粘贴历史有问题...

1. 卸载重装的话，数据可能会被清除的；
2. 另外macOS 11.x 系统是存在这个白屏问题的， 你升级App到3.7版本看看

**Comment by shuosiw** [comment]
嗯，已经更新了..感谢 👍
