### ISSUE TITLE
建议弹出候选粘贴内容框时给加上编号

### ISSUE THREAD

**Issue by zifeiYv** [MinMao-Hub/PasteEasy#14]
通过设置cmd+[1-9]可以快速粘贴历史内容，但一眼看到想要粘贴的内容在第几个位置有时候并不容易。因此，是否可以考虑给每个内容加上它所在位置的编号？

**Comment by MinMao-Hub** [comment]
> 通过设置cmd+[1-9]可以快速粘贴历史内容，但一眼看到想要粘贴的内容在第几个位置有时候并不容易。因此，是否可以考虑给每个内容加上它所在位置的编号？

因为这个编号会随着滚动而实时刷新的   直接展示的话就只能固定前9了 【之前用户反馈都希望这个编号是动态的】

**Comment by MinMao-Hub** [comment]
这边增加了一个折中的方案:

如果面板弹出的时候列表显示的内容是第一页，则主动显示快捷编号， 列表被滚动之后会隐藏编号
