### ISSUE TITLE
可以添加一个在焦点不在这个软件上的时候，也能用command快捷键粘贴吗？

### ISSUE THREAD

**Issue by Dylanmengzhou** [MinMao-Hub/PasteEasy#16]

**Comment by MinMao-Hub** [comment]
> _No description provided._
@Dylanmengzhou  这个功能之前也有人建议过，考虑到这些快捷键在很多软件里面用到了，会导致冲突，所以暂时搁置了

**PS：我将在后续版本中增加一个勾选选项，勾选之后可以在非聚焦的情况下直接通过Command快捷粘贴前9条`**

**Comment by Dylanmengzhou** [comment]
好的非常感谢

**Comment by MinMao-Hub** [comment]
@Dylanmengzhou  请更新到最新版本，然后勾选图示选项即可
![image](https://github.com/MinMao-Hub/PasteEasy/assets/9302381/d9cd38bf-8489-4a35-959f-193b1425703b)
