### ISSUE TITLE
软件打不开了，点了没反应

### ISSUE THREAD

**Issue by Leilllei** [MinMao-Hub/PasteEasy#17]
系统13.1，21年的16寸 M1 Pro机型，pasteeasy版本最新，另外微信群的二维码失效了

![image](https://user-images.githubusercontent.com/42111900/233824346-546cdf02-c576-45ea-b3fd-c9143c73d80d.png)

**Comment by MinMao-Hub** [comment]
麻烦说一下具体情况，点了没反应是在活动监视器中看不到是吗？还是？

另外，微信群二维码已更新。

**Comment by Leilllei** [comment]
是的，在活动监视器中没有pasteeasy的进程，点了之后也没有产生
