### ISSUE TITLE
提个建议，文件夹交互改成/或支持选择手风琴模式感觉会更实用一些

### ISSUE THREAD

**Issue by youthug** [MinMao-Hub/PasteEasy#18]
- 目前的样式：
  <img width="330" alt="image" src="https://user-images.githubusercontent.com/24794392/236107587-9d3c3042-25d8-417c-84df-a4ebd193afc6.png">

- 手风琴模式：
  <img width="1076" alt="image" src="https://user-images.githubusercontent.com/24794392/236107949-48a0eee8-744a-473b-abeb-e539809e59ba.png">

以及如果能支持文件夹自定义排序就更好啦 🪄

**Comment by MinMao-Hub** [comment]
@youthug 拖拽排序功能已添加， 手风琴样式暂时不安排了哈【主要还是放在屏幕底部使用的】
PS: 后续如果有更多的需求再安排😄
