### ISSUE TITLE
建议增加开机启动选项

### ISSUE THREAD

**Issue by strawHatYz** [MinMao-Hub/PasteEasy#19]

**Comment by MinMao-Hub** [comment]
> _No description provided._

@strawHatYz  建议看一下帮助文档 

https://github.com/MinMao-Hub/PasteEasy/blob/main/cn/help_launch.md

**Comment by strawHatYz** [comment]
好的，谢谢，app做的很棒，但是希望站在普通人的角度去考虑，毕竟不能让每个用户都看一遍帮助文档吧
