### ISSUE TITLE
再有一个默认快捷键的自定义就完美了

### ISSUE THREAD

**Issue by BrettDean** [MinMao-Hub/PasteEasy#2]
哈哈哈，加油

**Comment by MinMao-Hub** [comment]
你好，是指哪些快捷键呢 ？

**Comment by MinMao-Hub** [comment]
> 你好，是指哪些快捷键呢 ？



> 哈哈哈，加油

你好，是指哪些快捷键呢 ？

**Comment by MinMao-Hub** [comment]
> 哈哈哈，加油

你好，是指哪些快捷键呢 ？

**Comment by MinMao-Hub** [comment]
> > > 哈哈哈，加油
> > 
> > 
> > 你好，是指哪些快捷键呢 ？
> 
> 主要是`Command + 1~9`这个，因为我把默认的`⌘⇧V`改成`option+v`了。`option+v`显示 PasteEasy 面板以后大拇指还要切换到`cmd+1~9`就多了一步 😂

OK，下个版本支持修改这个修饰键 -  到时候可以从Command 、Option、Ctrl这三个键中选择

**Comment by MinMao-Hub** [comment]
请更新到3.5版本，然后在偏好设置中修改快捷粘贴主键

![f4f32bdda042a1723588dd49ccf3bbfc-imagen](https://user-images.githubusercontent.com/9302381/217406633-18734038-1159-49a9-910c-a211e778a906.png)
