### ISSUE TITLE
快捷键似乎不是全局的

### ISSUE THREAD

**Issue by Vast-Stars** [MinMao-Hub/PasteEasy#21]
我的唤醒快捷键设置为 option+` 
但是在别的窗口都无法唤醒，只有鼠标点击图标后，才有唤醒

**Comment by MinMao-Hub** [comment]
> 我的唤醒快捷键设置为 option+` 但是在别的窗口都无法唤醒，只有鼠标点击图标后，才有唤醒

这种特殊键一般都被系统占用了的。。。 建议设置没有被系统占用的快捷键

**Comment by MinMao-Hub** [comment]
> 我的唤醒快捷键设置为 option+` 但是在别的窗口都无法唤醒，只有鼠标点击图标后，才有唤醒

我现在用的 `Option + V `
