### ISSUE TITLE
分屏后PasteBoard无法跟随光标自动切换屏幕，一直处于主屏幕

### ISSUE THREAD

**Issue by jrovis** [MinMao-Hub/PasteEasy#22]
分屏后PasteBoard无法跟随光标自动切换屏幕，一直处于主屏幕，使用不便

**Comment by MinMao-Hub** [comment]
> 分屏后PasteBoard无法跟随光标自动切换屏幕，一直处于主屏幕，使用不便

看一下你的偏好设置，是否勾选 允许在扩展屏展示面板

![image](https://github.com/MinMao-Hub/PasteEasy/assets/9302381/89dfdd16-2d70-4de9-9821-b91d0e15e604)

**Comment by jrovis** [comment]
@MinMao-Hub 感谢大佬，原来是我没设置对 👍

**Comment by jrovis** [comment]
@MinMao-Hub 感谢大佬，原来是我没设置对 👍
