### ISSUE TITLE
[Feature Request] Allow to be installed from brew cask

### ISSUE THREAD

**Issue by nereuseng** [MinMao-Hub/PasteEasy#23]
Hi team, thanks for the feature added previously: #4. It works well from my side.

That would be great if we are able to install PasteEasy from brew cask: https://formulae.brew.sh/cask/

Thanks again for the work!

**Comment by MinMao-Hub** [comment]
> Hi team, thanks for the feature added previously: #4. It works well from my side.
> 
> That would be great if we are able to install PasteEasy from brew cask: https://formulae.brew.sh/cask/
> 
> Thanks again for the work!

Sorry, download from AppStore is only supported right now...
