### ISSUE TITLE
使用腾讯的lemon可以解决MacOS13.4打开闪退问题

### ISSUE THREAD

**Issue by Jude5201** [MinMao-Hub/PasteEasy#24]
使用腾讯的lemon可以解决13.4系统打开闪退问题：卸载功能里彻底卸载，并删除所有pasteEasy相关文件即可。

**Comment by MinMao-Hub** [comment]
> 使用腾讯的lemon可以解决13.4系统打开闪退问题：卸载功能里彻底卸载，并删除所有pasteEasy相关文件即可。

为了避免您的数据被删除，可以尝试使用修复器修复一下。
