### ISSUE TITLE
mac里右上角状态栏icon乌漆嘛黑的，希望调整下

### ISSUE THREAD

**Issue by watermelon-rider** [MinMao-Hub/PasteEasy#25]
<img width="35" alt="image" src="https://github.com/MinMao-Hub/PasteEasy/assets/110022603/61c0608e-7dab-4688-8b93-1fb6cdb9d122">

**Comment by MinMao-Hub** [comment]
> <img alt="image" width="35" src="https://user-images.githubusercontent.com/110022603/265581296-61c0608e-7dab-4688-8b93-1fb6cdb9d122.png">

@watermelon-rider   请升级您的App版本到3.8
