### ISSUE TITLE
paste easy 更新3.8版之后，Mac系统 Word中的文本不支持复制。

### ISSUE THREAD

**Issue by fangzhou8008** [MinMao-Hub/PasteEasy#27]
使用任何方式复制微软word for Mac中的文本，包括command+c，command+shift+c等方式，所复制的文本内容，都不能显示在pasteboard卡片中，但是所复制的图片依然可以进入到pasteboard。仅可以通过系统默认方式实现复制粘贴功能。word for Mac版本为16.77（23091003），系统为Ventura 13.5.

**Comment by MinMao-Hub** [comment]
> 使用任何方式复制微软word for Mac中的文本，包括command+c，command+shift+c等方式，所复制的文本内容，都不能显示在pasteboard卡片中，但是所复制的图片依然可以进入到pasteboard。仅可以通过系统默认方式实现复制粘贴功能。word for Mac版本为16.77（23091003），系统为Ventura 13.5.

请更新到3.9版本
