### ISSUE TITLE
新版 QQ 下复制图片未显示在历史记录

### ISSUE THREAD

**Issue by maxchang3** [MinMao-Hub/PasteEasy#28]
RT

QQ 版本: 6.9.20-17153

PasteEasy 版本 3.8

**Comment by MinMao-Hub** [comment]
> RT
> 
> QQ 版本: 6.9.20-17153
> 
> PasteEasy 版本 3.8

请更新到3.9版本

**Comment by maxchang3** [comment]
> 请更新到3.9版本

谢谢，已经更新，但是似乎还是不行。

<img width="194" alt="image" src="https://github.com/MinMao-Hub/PasteEasy/assets/36927158/5dc697fd-d067-4e73-9352-176df493a90e">

https://github.com/MinMao-Hub/PasteEasy/assets/36927158/095810ec-1300-484a-9bca-3f45e733c5c7

**Comment by maxchang3** [comment]
> 请更新到3.9版本

谢谢，已更新，但是还是不行。

https://github.com/MinMao-Hub/PasteEasy/assets/36927158/74c2da3b-4e95-494e-9d6a-868535eb3e15

**Comment by MinMao-Hub** [comment]
@maxchang3  其他地方的图片可以保存么？ 方便的话加一下我的微信： mp12860
PS: 我这边试了一下确实是没有问题的；QQ版本： 6.9.20-17153

**Comment by MinMao-Hub** [comment]
<img width="550" alt="image" src="https://github.com/MinMao-Hub/PasteEasy/assets/9302381/6bbc3105-cc80-4cf5-a1fe-95d0cd145a78">
还有麻烦确认一下这里是否正确勾选？ @maxchang3

**Comment by maxchang3** [comment]
> <img alt="image" width="550" src="https://user-images.githubusercontent.com/9302381/270674407-6bbc3105-cc80-4cf5-a1fe-95d0cd145a78.png"> 还有麻烦确认一下这里是否正确勾选？ @maxchang3

勾选了， 已经可以正常工作……原来被算成文件了，之前未勾选似乎是可用的，谢谢！
