### ISSUE TITLE
面板自定义功能消失了

### ISSUE THREAD

**Issue by lizonglin2010** [MinMao-Hub/PasteEasy#29]
卡片背景以前是可以自定义的，但在新版本被强制设定成了毛玻璃，希望恢复自定义，给用户一些自由发挥的机会
之前的卡片背景自定义面板：
<img width="325" alt="截屏2023-09-27 13 52 58" src="https://github.com/MinMao-Hub/PasteEasy/assets/85780935/ab3e11f4-d1a8-4b94-bab2-166c926fb360">

BTW，感觉纯色填充的卡片也可以很好看，类似这种的样子：
<img width="337" alt="截屏2023-09-27 13 48 43" src="https://github.com/MinMao-Hub/PasteEasy/assets/85780935/27469312-f003-44a8-a52d-d80539000caf">

**Comment by MinMao-Hub** [comment]
![image](https://github.com/MinMao-Hub/PasteEasy/assets/9302381/e7b4796c-07a1-48f6-8202-f760bc18d99b)
@lizonglin2010  请看一下这个地方是选了哪个选项？

**Comment by lizonglin2010** [comment]
> ![image](https://user-images.githubusercontent.com/9302381/270880332-e7b4796c-07a1-48f6-8202-f760bc18d99b.png)
> @lizonglin2010 请看一下这个地方是选了哪个选项？

样式恢复了！太棒啦！
