### ISSUE TITLE
复制到面板的内容是白色文字

### ISSUE THREAD

**Issue by qiaoro** [MinMao-Hub/PasteEasy#3]
如图：
<img width="306" alt="image" src="https://user-images.githubusercontent.com/8346983/209749976-02d8d20e-b1a0-4356-bba6-9ce2dca7cb31.png">

**Comment by MinMao-Hub** [comment]
> 如图： <img alt="image" width="306" src="https://user-images.githubusercontent.com/8346983/209749976-02d8d20e-b1a0-4356-bba6-9ce2dca7cb31.png">

读取到的文字颜色和背景色都是白色， 预览界面能看到文字么？  方便的话贴一下复制来源网站，我这边尽快排查修复一下

**Comment by qiaoro** [comment]
<img width="680" alt="image" src="https://user-images.githubusercontent.com/8346983/209750742-e610b9d3-cc6e-4c45-ad8c-a8f835c5ab25.png">
F12 里的 network。随意一个请求的 信息 选中复制 就这样

**Comment by MinMao-Hub** [comment]
> <img alt="image" width="680" src="https://user-images.githubusercontent.com/8346983/209750742-e610b9d3-cc6e-4c45-ad8c-a8f835c5ab25.png">
> 
> F12 里的 network。随意一个请求的 信息 选中复制 就这样

已复现，将在下个版本中优化，谢谢反馈

**Comment by MinMao-Hub** [comment]
该问题已在3.5修复，请更新

**Comment by qiaoro** [comment]
<img width="315" alt="image" src="https://user-images.githubusercontent.com/8346983/217411226-76b2b6a1-7031-49b6-a243-8ec08c8861e3.png">
问题修复了， 但是看起来好难受，想问下富文本和文本的识别是咋样呀？ 我记得以前全是文本类型的，但现在全是富文本类型，很多场景里其实并不希望粘贴的时候含有原有格式。

**Comment by MinMao-Hub** [comment]
优先取富文本，如果取到富文本就是富文本了；你可以在偏好设置中修改默认粘贴数据样式
参考： https://github.com/MinMao-Hub/PasteEasy/issues/4

**Comment by MinMao-Hub** [comment]
在3.7版本中增加了卡片显示样式选择，如果不喜欢富文本显示的话，直接选择纯文本显示【纯文本可以定制自己喜欢的颜色、字号等】

![01237052e5b3126588a0fdaa54ca0ea1](https://user-images.githubusercontent.com/9302381/227822078-fa4e2a7f-8c8b-41dc-90c0-00255f694001.png)
