### ISSUE TITLE
應用程式執行時會導致不能剪下貼上

### ISSUE THREAD

**Issue by darkjackx** [MinMao-Hub/PasteEasy#30]
command + c => command + v  可以
但command + c => command + option + v   不行

**Comment by MinMao-Hub** [comment]
> command + c => command + v 可以 但command + c => command + option + v 不行

麻烦描述的再详细一点， 我没弄清楚  command + option + v  是干啥用的？或者可以微信直接联系我: mp12860 @darkjackx

**Comment by MinMao-Hub** [comment]
这个问题是在复制文件的时候发生的对么？command + option + v会改变文件路径，而PasteEasy存储了原先的文件路径，所以就肯定找不到文件了 - 你这个操作相当于删除了文件；

如果是非文件操作，麻烦再详细描述一下，或者加微信群【首页有二维码】反馈一下

**Comment by darkjackx** [comment]
不好意思... 發現問題了, 原來快捷鍵衝突了

「小冒 ***@***.***>」在 2023年10月7日 週六，上午9:57 寫道：
