### ISSUE TITLE
Most copied text is now unknown characters

### ISSUE THREAD

**Issue by matt-unosquare** [MinMao-Hub/PasteEasy#31]
I think this happened about the same time as the latest MacOS update, but now most of the text I copy in VSCode is now just displaying as unknown characters

![image](https://github.com/MinMao-Hub/PasteEasy/assets/126695488/cb14abc5-a2ee-4d1b-9382-fa7c316a843b)
![image](https://github.com/MinMao-Hub/PasteEasy/assets/126695488/d3a97ff8-f876-4512-8fe0-f5d446f1401f)

**Comment by MinMao-Hub** [comment]
@matt-unosquare Hi, what is your VSCode version number? I just tried it here. It is normal to use it.

Here is my VSCode version information and system version information:
![image](https://github.com/MinMao-Hub/PasteEasy/assets/9302381/d4d38525-07bd-4a2f-85bf-87684a070e9d)
![image](https://github.com/MinMao-Hub/PasteEasy/assets/9302381/ccc18d7c-9d8b-4c6a-9ca3-f35290202812)

**Comment by MinMao-Hub** [comment]
![image](https://github.com/MinMao-Hub/PasteEasy/assets/9302381/b124e125-5830-4b85-b861-83bc7dd887e3)

**Comment by MinMao-Hub** [comment]
Hey, after investigation, it is found that this is a text encoding compatibility problem of VSCode.delete this line in your VSCode settings, and then copy the text to see
<img width="733" alt="image" src="https://github.com/MinMao-Hub/PasteEasy/assets/9302381/974815bf-a4aa-41ee-9e39-910fefdd15a9">

**Comment by MinMao-Hub** [comment]
If it still doesn't work, then the card display style here should be set to plain text.
![image](https://github.com/MinMao-Hub/PasteEasy/assets/9302381/c9f68041-19e7-41e0-aa08-5a9a3ec3a474)

**Comment by matt-unosquare** [comment]
You are correct, it is a problem with the `"editor.fontFamily"` settings. This was working previously, but appears to be broken now. Thank you for digging into this, for now I can just not override my font i suppose

**Comment by MinMao-Hub** [comment]
> You are correct, it is a problem with the `"editor.fontFamily"` settings. This was working previously, but appears to be broken now. Thank you for digging into this, for now I can just not override my font i suppose

You can also use this method to avoid modifying your `"editor.fontFamily"` settings
https://github.com/MinMao-Hub/PasteEasy/issues/31#issuecomment-1751647846
