### ISSUE TITLE
Vscode文本乱码

### ISSUE THREAD

**Issue by topazur** [MinMao-Hub/PasteEasy#32]
<img width="496" alt="image" src="https://github.com/MinMao-Hub/PasteEasy/assets/88650465/773d0f31-03fe-4263-88a1-9cc255495060">

Version: PasteEasy 3.9
OS: macOS 14.0 （升级新系统之后发现的，13版本是正常的）
remark: 仅显示乱码（不知道内容是什么），但是粘贴后结果正常。

**Comment by MinMao-Hub** [comment]
https://github.com/MinMao-Hub/PasteEasy/issues/31
