### ISSUE TITLE
无法自动粘贴

### ISSUE THREAD

**Issue by yanghahaha** [MinMao-Hub/PasteEasy#35]
操作系统：OSX 13.6
软件版本：3.9
现象：
1. Auto paste to active app 已开启
2. Command + shift + V 打开 panel 后，双击 或 Enter 都无法将内容粘贴到当前 app，需要再 Command + V 才行
(我试过 wechat wecom phpstorm notes telgram)

**Comment by MinMao-Hub** [comment]
@yanghahaha  直接使用方法3即可；
![image](https://github.com/MinMao-Hub/PasteEasy/assets/9302381/91e4f188-8de8-4389-9f07-5b2f1bb02692)

PS: 后续有问题优先请查看一下[帮助文档](https://github.com/MinMao-Hub/PasteEasy/tree/main/cn)哈，谢谢！

**Comment by yanghahaha** [comment]
Problem solved, many thanks for your support.

**Comment by yanghahaha** [comment]
补充解决流程：
发现在 accessibility 中无法关闭 pasteEasy
最终使用了方法3解决
