### ISSUE TITLE
Text of VSCode and other apps not supported after update of macOS Sonoma 14.0

### ISSUE THREAD

**Issue by sbimochan** [MinMao-Hub/PasteEasy#36]
It appears to be like this. Wherea's other simple texts like from browser URL seems to be fine.

It appears to be wrong when texts are formatted.

<img width="254" alt="Screenshot 2023-11-22 at 5 11 56 PM" src="https://github.com/MinMao-Hub/PasteEasy/assets/11685953/4e21f5a8-aedd-4326-9f00-2749f636366e">

**Comment by MinMao-Hub** [comment]
Please check out the same issues： https://github.com/MinMao-Hub/PasteEasy/issues/31
