### ISSUE TITLE
盯起来内容被自动删除了

### ISSUE THREAD

**Issue by liyuze** [MinMao-Hub/PasteEasy#37]
环境：
M1 Pro 14 
macOS：14.2.1 (23C71)
PasteEasy 3.9

复现步骤如下：
1. 选择只保存最近的10条记录。
1. 复制 word.   在面板里钉到【常用】里。
1. 继续复制其他内容超过10条。
2. 按下快捷键弹出面板

效果：
word  在【Passboard】 里删除掉，在【常用】面板里也删除了。

期望：
在【常用】面板里正常保留（钉起来的内容不应自动删除）

**Comment by MinMao-Hub** [comment]
新版本已发布，请更新到4.0版本 @liyuze
