### ISSUE TITLE
[Feature Request] Provide an option to configure the default behaviour of pasting

### ISSUE THREAD

**Issue by nereuseng** [MinMao-Hub/PasteEasy#4]
Hey team, thanks for the amazing work, I really like this app!

Are there any plans to add an option in preference, that we change configure the default behaviour of pasting? Reason of asking this, is because it's quite annoying to me to copy codes from VS Code to google doc, the styles will be copied. Here is the example:

<img width="624" alt="image" src="https://user-images.githubusercontent.com/11313394/209767543-b2a96cf5-2122-49af-bd9e-c1dde5543d6c.png">

Please let me know if you need anything to clarify, thanks!

**Comment by MinMao-Hub** [comment]
> Hey team, thanks for the amazing work, I really like this app!
> 
> Are there any plans to add an option in preference, that we change configure the default behaviour of pasting? Reason of asking this, is because it's quite annoying to me to copy codes from VS Code to google doc, the styles will be copied. Here is the example:
> 
> <img alt="image" width="624" src="https://user-images.githubusercontent.com/11313394/209767543-b2a96cf5-2122-49af-bd9e-c1dde5543d6c.png">
> 
> Please let me know if you need anything to clarify, thanks!

Thank you for your feedback. This suggestion has been recorded and will be considered in future versions.

**Comment by MinMao-Hub** [comment]
Please update to version 3.5, Then modify this option:

![3fd6c5b03460ecd8599616b498e854d8-imagen](https://user-images.githubusercontent.com/9302381/217406296-fb4e06ba-f8de-409e-af38-d6a4f50b41b6.png)
