### ISSUE TITLE
无法打开偏好设置

### ISSUE THREAD

**Issue by julian20220130** [MinMao-Hub/PasteEasy#44]
老用户了，近期才发现此问题。软件版本 3.9，复制粘贴功能均能正常使用，但无论是从主页面还是菜单栏，均无法打开偏好设置页面，使用快捷键 command+ ，的话软件会直接退出。重启软件和电脑也不行。
此外还有一个小 bug，就是主页面上窗口的文字在唤醒的时候会被切掉一部分，只有重启软件后第一次唤醒是能够正常显示的。
22 年 MacBook Air，Sonoma 14.0。
![image](https://github.com/MinMao-Hub/PasteEasy/assets/98684721/69f2e15a-f046-474b-ab16-7d4c0cc6da70)

![image](https://github.com/MinMao-Hub/PasteEasy/assets/98684721/5b28213e-f1ae-4fca-bfc5-bcdc8a001e98)

**Comment by MinMao-Hub** [comment]
收到，以上问题会在下个版本修复  @julian20220130
