### ISSUE TITLE
Mac 15 beta， 不能用了！！！

### ISSUE THREAD

**Issue by fanyu** [MinMao-Hub/PasteEasy#45]

**Comment by MinMao-Hub** [comment]
收到👌🏻   我系统还没升级。。。。 等我升级了看看 @fanyu

**Comment by fanyu** [comment]
hi，有测试版了么

**Comment by fanyu** [comment]
升级新beta可以用了，但是Option+快捷键，不能用了。command+的可以用

**Comment by MinMao-Hub** [comment]
抱歉了，Beta版本系统不稳定因素太多，暂时不做适配【等15正式版发布之后会统一进行适配】
