### ISSUE TITLE
自动复制，以及面板跟随

### ISSUE THREAD

**Issue by sunpei-zju** [MinMao-Hub/PasteEasy#47]
作者你好，
首先感谢你的软件！在使用中发现一个问题以及一个建议：
1. 现在每次在word里选中文字都会自动复制进卡片，有时候其实并不需要复制的，只是有选中部分词句的习惯，无谓多了很多没用的内容。
2. 不知能否让面板跟随光标，类似windows的多内容剪切板卡片，这样选择起来会方便一些。

**Comment by MinMao-Hub** [comment]
你好
关于问题1： 自动复制操作应该是你的word设置或者某些选词软件导致的，本应用仅读取剪切板里面的内容。
关于问题2：目前因为设计上是全屏展示的，如果跟随光标的话会出现显示异常【后续可能会考虑更小的展示区域，跟随光标悬浮显示在屏幕上】
