### ISSUE TITLE
请问这是怎么回事，输入 1 以后自动弹出这些字，像是之前的粘贴板里的内容。

### ISSUE THREAD

**Issue by kscMaster** [MinMao-Hub/PasteEasy#49]
![PixPin_2024-12-04_11-56-18](https://github.com/user-attachments/assets/bcc30b77-3813-470c-b4c6-44e94bd0e0e4)
![PixPin_2024-12-04_15-09-49](https://github.com/user-attachments/assets/f215e8b0-ed34-4bfb-9153-a6857a078ca9)

**Comment by MinMao-Hub** [comment]
@kscMaster  你这个是装了其他软件吧？ 我这个应用没有这个功能哇

**Comment by kscMaster** [comment]
抱歉，我也一直在调整设置，最后把应用关了发现还有这个问题，最后定位到，不知道怎么加了一个自定义短语，sorry哈
