### ISSUE TITLE
最新版本，每次关机或者重启电脑，所有的记录都被清空了，记得之前版本不会的呢

### ISSUE THREAD

**Issue by pizhiyong** [MinMao-Hub/PasteEasy#5]

**Comment by MinMao-Hub** [comment]
请排查数据是否被你安装的清理软件给清除了？ 数据存储在：
/Users/xxx/Library/Containers/com.minmao.paste/Data/Library/Application\ Support/PasteEasy/pastedata.thumb  这个数据库中，重新启动电脑之后看一下这个文件的大小

**Comment by pizhiyong** [comment]
> 请排查数据是否被你安装的清理软件给清除了？ 数据存储在： /Users/xxx/Library/Containers/com.minmao.paste/Data/Library/Application\ Support/PasteEasy/pastedata.thumb 这个数据库中，重新启动电脑之后看一下这个文件的大小

重启了电脑，应该是数据被清除了。但由于是公司电脑，有办法能避免数据被清除吗？

**Comment by MinMao-Hub** [comment]
> > 请排查数据是否被你安装的清理软件给清除了？ 数据存储在： /Users/xxx/Library/Containers/com.minmao.paste/Data/Library/Application\ Support/PasteEasy/pastedata.thumb 这个数据库中，重新启动电脑之后看一下这个文件的大小
> 
> 重启了电脑，应该是数据被清除了。但由于是公司电脑，有办法能避免数据被清除吗？

你还个要么是被清理软件自动清理了，要么是被系统清理了【系统清理的话一般是硬盘空间不足了。。】。
1. 如果是清理软件的话，你可以尝试设置清理白名单之类的。
2. 如果是系统清理的话，只能清理别的冗余内容，留出足够的存储空间

PS：后续版本可能会考虑换个地方存储数据，防止被系统清理

**Comment by MinMao-Hub** [comment]
该问题已在3.5修复，请更新
