### ISSUE TITLE
扩展屏幕在全屏模式时【允许在扩展屏幕上显示面板】选项失效

### ISSUE THREAD

**Issue by qq173924384** [MinMao-Hub/PasteEasy#6]

**Comment by eavlee** [comment]
+1

**Comment by MinMao-Hub** [comment]
这个问题目前暂未找到解决方案，目前发现没有任何应用能显示在副屏幕全屏模式上...   
PS: 如果有请举例   我再排查 
@qq173924384 @eavlee

**Comment by eavlee** [comment]
> 这个问题目前暂未找到解决方案，目前发现没有任何应用能显示在副屏幕全屏模式上... PS: 如果有请举例 我再排查 @qq173924384 @eavlee

展示在副屏幕的全屏模式的应用，iterm2是可以的。
然后有个同类的软件 Pasty ，也是可以在副屏全屏模式下唤出的，可以在App store搜到，只不过好像很久没更新了。

![image](https://github.com/user-attachments/assets/31487441-56ca-4bbf-8624-f42bd0422702)
