### ISSUE TITLE
开机启动的时候，可不可以设置不弹出来？

### ISSUE THREAD

**Issue by lleng** [MinMao-Hub/PasteEasy#7]
如题，非常好用的工具！o(￣▽￣)ｄ
但是关机重启之后会自动打开显示之前复制的内容，会有一些敏感内容在，不是很方便。考虑加个无感自启动的功能吗？❤️

**Comment by MinMao-Hub** [comment]
> 如题，非常好用的工具！o(￣▽￣)ｄ 但是关机重启之后会自动打开显示之前复制的内容，会有一些敏感内容在，不是很方便。考虑加个无感自启动的功能吗？❤️

好哒~  后续版本可以支持

**Comment by MinMao-Hub** [comment]
请更新到3.5版本， 偏好设置 => 更多 => 取消勾选启动时显示面板选项即可

![e17e743c827ef7885af31edb839436b1-imagen](https://user-images.githubusercontent.com/9302381/217405789-8265190b-ddbf-4844-a418-7986b6c575d8.png)
