### ISSUE TITLE
能否不自动粘贴，或者增加一个自动粘贴开关

### ISSUE THREAD

**Issue by Nonable** [MinMao-Hub/PasteEasy#8]
现在回车、双击（右键提取MD5等）都是自动粘贴了，能否增加一个开关，是否开启自动粘贴功能~

**Comment by MinMao-Hub** [comment]
> 现在回车、双击（右键提取MD5等）都是自动粘贴了，能否增加一个开关，是否开启自动粘贴功能~

你可以尝试Command + C  【仅复制，不粘贴】

**Comment by Nonable** [comment]
> > 现在回车、双击（右键提取MD5等）都是自动粘贴了，能否增加一个开关，是否开启自动粘贴功能~
> 
> 你可以尝试Command + C 【仅复制，不粘贴】

右键提取MD5、右键识别二维码等右键操作，是自动粘贴的~

**Comment by MinMao-Hub** [comment]
> > > 现在回车、双击（右键提取MD5等）都是自动粘贴了，能否增加一个开关，是否开启自动粘贴功能~
> > 
> > 
> > 你可以尝试Command + C 【仅复制，不粘贴】
> 
> 右键提取MD5、右键识别二维码等右键操作，是自动粘贴的~

行  后续版本考虑价格自动粘贴关闭选项~     勾选则关闭自动粘贴

**Comment by MinMao-Hub** [comment]
请更新到3.5版本， 偏好设置 => 更多 => 取消勾选自动粘贴选项即可

![a214a2dd570a93f03219f38991d3cef4-imagen](https://user-images.githubusercontent.com/9302381/217405661-dbc42516-1f6d-4972-b545-5068123cf5d3.png)
